version: "3.9"
services:
    rabbit:
        image: rabbitmq:3.8-management
        container_name: "rabbit-test"
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - dns
        environment:
            RABBITMQ_DEFAULT_USER: root
            RABBITMQ_DEFAULT_PASS: 123456
    redis:
        image: redis:3.2.10
        container_name: "redis-test"
        ports:
            - "6379:6379"
networks:
    dns:
        name: "dns"
        driver: "bridge"
